// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class Map {
        
        private Gtk.EventBox eventbox1;
        
        private Gtk.Image image;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.Map
            Stetic.BinContainer.Attach(this);
            this.Name = "omvviewerlight.Map";
            // Container child omvviewerlight.Map.Gtk.Container+ContainerChild
            this.eventbox1 = new Gtk.EventBox();
            this.eventbox1.Name = "eventbox1";
            // Container child eventbox1.Gtk.Container+ContainerChild
            this.image = new Gtk.Image();
            this.image.Events = ((Gdk.EventMask)(256));
            this.image.ExtensionEvents = ((Gdk.ExtensionMode)(1));
            this.image.Name = "image";
            this.eventbox1.Add(this.image);
            this.Add(this.eventbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.eventbox1.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox1ButtonPressEvent);
        }
    }
}
