// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class Friendshiprequest {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label label_info;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button button_accept;
        
        private Gtk.Button button3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.Friendshiprequest
            this.Name = "omvviewerlight.Friendshiprequest";
            this.Title = Mono.Unix.Catalog.GetString("Friendship request");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child omvviewerlight.Friendshiprequest.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label_info = new Gtk.Label();
            this.label_info.HeightRequest = 59;
            this.label_info.Name = "label_info";
            this.label_info.LabelProp = Mono.Unix.Catalog.GetString("label2");
            this.vbox1.Add(this.label_info);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.label_info]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button_accept = new Gtk.Button();
            this.button_accept.CanFocus = true;
            this.button_accept.Name = "button_accept";
            this.button_accept.UseUnderline = true;
            this.button_accept.Label = Mono.Unix.Catalog.GetString("Accept");
            this.hbox1.Add(this.button_accept);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.button_accept]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button3 = new Gtk.Button();
            this.button3.CanFocus = true;
            this.button3.Name = "button3";
            this.button3.UseUnderline = true;
            this.button3.Label = Mono.Unix.Catalog.GetString("Reject");
            this.hbox1.Add(this.button3);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.button3]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 121;
            this.Show();
            this.button_accept.Clicked += new System.EventHandler(this.OnButtonAcceptClicked);
            this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
        }
    }
}
