// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class LocalRegion {
        
        private Gtk.VBox vbox3;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox4;
        
        private Gtk.EventBox eventbox1;
        
        private Gtk.Image image1;
        
        private Gtk.EventBox eventbox2;
        
        private Gtk.Image image2;
        
        private Gtk.EventBox eventbox3;
        
        private Gtk.Image image3;
        
        private Gtk.HBox hbox5;
        
        private Gtk.EventBox eventbox4;
        
        private Gtk.Image image4;
        
        private Gtk.EventBox eventbox5;
        
        private Gtk.Image image5;
        
        private Gtk.EventBox eventbox6;
        
        private Gtk.Image image6;
        
        private Gtk.HBox hbox6;
        
        private Gtk.EventBox eventbox7;
        
        private Gtk.Image image7;
        
        private Gtk.EventBox eventbox8;
        
        private Gtk.Image image8;
        
        private Gtk.EventBox eventbox9;
        
        private Gtk.Image image9;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.LocalRegion
            Stetic.BinContainer.Attach(this);
            this.Name = "omvviewerlight.LocalRegion";
            // Container child omvviewerlight.LocalRegion.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            // Container child hbox4.Gtk.Box+BoxChild
            this.eventbox1 = new Gtk.EventBox();
            this.eventbox1.Name = "eventbox1";
            // Container child eventbox1.Gtk.Container+ContainerChild
            this.image1 = new Gtk.Image();
            this.image1.WidthRequest = 100;
            this.image1.HeightRequest = 100;
            this.image1.Name = "image1";
            this.eventbox1.Add(this.image1);
            this.hbox4.Add(this.eventbox1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox4[this.eventbox1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.eventbox2 = new Gtk.EventBox();
            this.eventbox2.Name = "eventbox2";
            // Container child eventbox2.Gtk.Container+ContainerChild
            this.image2 = new Gtk.Image();
            this.image2.WidthRequest = 100;
            this.image2.HeightRequest = 100;
            this.image2.Name = "image2";
            this.eventbox2.Add(this.image2);
            this.hbox4.Add(this.eventbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox4[this.eventbox2]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.eventbox3 = new Gtk.EventBox();
            this.eventbox3.Name = "eventbox3";
            // Container child eventbox3.Gtk.Container+ContainerChild
            this.image3 = new Gtk.Image();
            this.image3.WidthRequest = 100;
            this.image3.HeightRequest = 100;
            this.image3.Name = "image3";
            this.eventbox3.Add(this.image3);
            this.hbox4.Add(this.eventbox3);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox4[this.eventbox3]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            this.vbox4.Add(this.hbox4);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.WidthRequest = 100;
            this.hbox5.HeightRequest = 100;
            this.hbox5.Name = "hbox5";
            // Container child hbox5.Gtk.Box+BoxChild
            this.eventbox4 = new Gtk.EventBox();
            this.eventbox4.Name = "eventbox4";
            // Container child eventbox4.Gtk.Container+ContainerChild
            this.image4 = new Gtk.Image();
            this.image4.WidthRequest = 100;
            this.image4.HeightRequest = 100;
            this.image4.Name = "image4";
            this.eventbox4.Add(this.image4);
            this.hbox5.Add(this.eventbox4);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox5[this.eventbox4]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.eventbox5 = new Gtk.EventBox();
            this.eventbox5.Name = "eventbox5";
            // Container child eventbox5.Gtk.Container+ContainerChild
            this.image5 = new Gtk.Image();
            this.image5.WidthRequest = 100;
            this.image5.HeightRequest = 100;
            this.image5.Name = "image5";
            this.eventbox5.Add(this.image5);
            this.hbox5.Add(this.eventbox5);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox5[this.eventbox5]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.eventbox6 = new Gtk.EventBox();
            this.eventbox6.Name = "eventbox6";
            // Container child eventbox6.Gtk.Container+ContainerChild
            this.image6 = new Gtk.Image();
            this.image6.WidthRequest = 100;
            this.image6.HeightRequest = 100;
            this.image6.Name = "image6";
            this.eventbox6.Add(this.image6);
            this.hbox5.Add(this.eventbox6);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox5[this.eventbox6]));
            w13.Position = 2;
            w13.Expand = false;
            w13.Fill = false;
            this.vbox4.Add(this.hbox5);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            // Container child hbox6.Gtk.Box+BoxChild
            this.eventbox7 = new Gtk.EventBox();
            this.eventbox7.Name = "eventbox7";
            // Container child eventbox7.Gtk.Container+ContainerChild
            this.image7 = new Gtk.Image();
            this.image7.WidthRequest = 100;
            this.image7.HeightRequest = 100;
            this.image7.Name = "image7";
            this.eventbox7.Add(this.image7);
            this.hbox6.Add(this.eventbox7);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox6[this.eventbox7]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.eventbox8 = new Gtk.EventBox();
            this.eventbox8.Name = "eventbox8";
            // Container child eventbox8.Gtk.Container+ContainerChild
            this.image8 = new Gtk.Image();
            this.image8.WidthRequest = 100;
            this.image8.HeightRequest = 100;
            this.image8.Name = "image8";
            this.eventbox8.Add(this.image8);
            this.hbox6.Add(this.eventbox8);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox6[this.eventbox8]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.eventbox9 = new Gtk.EventBox();
            this.eventbox9.Name = "eventbox9";
            // Container child eventbox9.Gtk.Container+ContainerChild
            this.image9 = new Gtk.Image();
            this.image9.WidthRequest = 100;
            this.image9.HeightRequest = 100;
            this.image9.Name = "image9";
            this.eventbox9.Add(this.image9);
            this.hbox6.Add(this.eventbox9);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox6[this.eventbox9]));
            w20.Position = 2;
            w20.Expand = false;
            w20.Fill = false;
            this.vbox4.Add(this.hbox6);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
            w21.Position = 2;
            w21.Expand = false;
            w21.Fill = false;
            this.vbox3.Add(this.vbox4);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
            w22.Position = 0;
            w22.Expand = false;
            w22.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.eventbox1.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox1ButtonPressEvent);
            this.eventbox2.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox2ButtonPressEvent);
            this.eventbox3.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox3ButtonPressEvent);
            this.eventbox4.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox4ButtonPressEvent);
            this.eventbox5.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox5ButtonPressEvent);
            this.eventbox6.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox6ButtonPressEvent);
            this.eventbox7.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox7ButtonPressEvent);
            this.eventbox8.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox8ButtonPressEvent);
            this.eventbox9.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventbox9ButtonPressEvent);
        }
    }
}
