// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class LocalRegion {
        
        private Gtk.EventBox eventbox_master;
        
        private Gtk.HBox hbox2;
        
        private Gtk.VBox vbox2;
        
        private omvviewerlight.Map map1;
        
        private omvviewerlight.Map map4;
        
        private omvviewerlight.Map map7;
        
        private Gtk.VBox vbox3;
        
        private omvviewerlight.Map map2;
        
        private omvviewerlight.Map map5;
        
        private omvviewerlight.Map map8;
        
        private Gtk.VBox vbox4;
        
        private omvviewerlight.Map map3;
        
        private omvviewerlight.Map map6;
        
        private omvviewerlight.Map map9;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.LocalRegion
            Stetic.BinContainer.Attach(this);
            this.Name = "omvviewerlight.LocalRegion";
            // Container child omvviewerlight.LocalRegion.Gtk.Container+ContainerChild
            this.eventbox_master = new Gtk.EventBox();
            this.eventbox_master.Name = "eventbox_master";
            // Container child eventbox_master.Gtk.Container+ContainerChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            // Container child vbox2.Gtk.Box+BoxChild
            this.map1 = new omvviewerlight.Map();
            this.map1.Events = ((Gdk.EventMask)(256));
            this.map1.Name = "map1";
            this.vbox2.Add(this.map1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.map1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.map4 = new omvviewerlight.Map();
            this.map4.Events = ((Gdk.EventMask)(256));
            this.map4.Name = "map4";
            this.vbox2.Add(this.map4);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.map4]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.map7 = new omvviewerlight.Map();
            this.map7.Events = ((Gdk.EventMask)(256));
            this.map7.Name = "map7";
            this.vbox2.Add(this.map7);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.map7]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.hbox2.Add(this.vbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            // Container child vbox3.Gtk.Box+BoxChild
            this.map2 = new omvviewerlight.Map();
            this.map2.Events = ((Gdk.EventMask)(256));
            this.map2.Name = "map2";
            this.vbox3.Add(this.map2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.map2]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.map5 = new omvviewerlight.Map();
            this.map5.Events = ((Gdk.EventMask)(256));
            this.map5.Name = "map5";
            this.vbox3.Add(this.map5);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.map5]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.map8 = new omvviewerlight.Map();
            this.map8.Events = ((Gdk.EventMask)(256));
            this.map8.Name = "map8";
            this.vbox3.Add(this.map8);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox3[this.map8]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            this.hbox2.Add(this.vbox3);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            // Container child vbox4.Gtk.Box+BoxChild
            this.map3 = new omvviewerlight.Map();
            this.map3.Events = ((Gdk.EventMask)(256));
            this.map3.Name = "map3";
            this.vbox4.Add(this.map3);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox4[this.map3]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.map6 = new omvviewerlight.Map();
            this.map6.Events = ((Gdk.EventMask)(256));
            this.map6.Name = "map6";
            this.vbox4.Add(this.map6);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox4[this.map6]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.map9 = new omvviewerlight.Map();
            this.map9.Events = ((Gdk.EventMask)(256));
            this.map9.Name = "map9";
            this.vbox4.Add(this.map9);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox4[this.map9]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            this.hbox2.Add(this.vbox4);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            this.eventbox_master.Add(this.hbox2);
            this.Add(this.eventbox_master);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
