// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class PayWindow {
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label label_payinfo;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label label11;
        
        private Gtk.Entry entry1;
        
        private Gtk.Label label12;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Button button_pay;
        
        private Gtk.Button button_cancel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.PayWindow
            this.Name = "omvviewerlight.PayWindow";
            this.Title = Mono.Unix.Catalog.GetString("Pay");
            this.Icon = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./status_money.png"));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            // Container child omvviewerlight.PayWindow.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label_payinfo = new Gtk.Label();
            this.label_payinfo.Name = "label_payinfo";
            this.label_payinfo.LabelProp = Mono.Unix.Catalog.GetString("Pay \nResident Michelle2 Zenovka\n");
            this.label_payinfo.Justify = ((Gtk.Justification)(2));
            this.vbox3.Add(this.label_payinfo);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox3[this.label_payinfo]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            this.hbox5.BorderWidth = ((uint)(3));
            // Container child hbox5.Gtk.Box+BoxChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Amount");
            this.hbox5.Add(this.label11);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox5[this.label11]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.entry1 = new Gtk.Entry();
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.WidthChars = 10;
            this.entry1.MaxLength = 10;
            this.entry1.InvisibleChar = '●';
            this.hbox5.Add(this.entry1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox5[this.entry1]));
            w3.Position = 1;
            w3.Expand = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("$L");
            this.hbox5.Add(this.label12);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox5[this.label12]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox4.Add(this.hbox5);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox5]));
            w5.Position = 0;
            w5.Fill = false;
            this.vbox3.Add(this.vbox4);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Homogeneous = true;
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.button_pay = new Gtk.Button();
            this.button_pay.CanFocus = true;
            this.button_pay.Name = "button_pay";
            this.button_pay.UseUnderline = true;
            // Container child button_pay.Gtk.Container+ContainerChild
            Gtk.Alignment w7 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w8 = new Gtk.HBox();
            w8.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w9 = new Gtk.Image();
            w9.Pixbuf = MainClass.GetResource("status_money.png");
            w8.Add(w9);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w11 = new Gtk.Label();
            w11.LabelProp = Mono.Unix.Catalog.GetString("Pay");
            w11.UseUnderline = true;
            w8.Add(w11);
            w7.Add(w8);
            this.button_pay.Add(w7);
            this.hbox4.Add(this.button_pay);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox4[this.button_pay]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.button_cancel = new Gtk.Button();
            this.button_cancel.CanFocus = true;
            this.button_cancel.Name = "button_cancel";
            this.button_cancel.UseUnderline = true;
            // Container child button_cancel.Gtk.Container+ContainerChild
            Gtk.Alignment w16 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w17 = new Gtk.HBox();
            w17.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w18 = new Gtk.Image();
            w18.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Menu, 16);
            w17.Add(w18);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w20 = new Gtk.Label();
            w20.LabelProp = Mono.Unix.Catalog.GetString("Cancel");
            w20.UseUnderline = true;
            w17.Add(w20);
            w16.Add(w17);
            this.button_cancel.Add(w16);
            this.hbox4.Add(this.button_cancel);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox4[this.button_cancel]));
            w24.Position = 1;
            w24.Expand = false;
            w24.Fill = false;
            this.vbox3.Add(this.hbox4);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
            w25.Position = 2;
            w25.Expand = false;
            w25.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 155;
            this.Show();
            this.button_pay.Clicked += new System.EventHandler(this.OnButtonPayClicked);
            this.button_cancel.Clicked += new System.EventHandler(this.OnButtonCancelClicked);
        }
    }
}
