// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class ChatLayout {
        
        private Gtk.HPaned hpaned1;
        
        private omvviewerlight.ChatConsole chatconsole1;
        
        private Gtk.VPaned vpaned1;
        
        private omvviewerlight.FriendsList friendslist1;
        
        private omvviewerlight.Radar radar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.ChatLayout
            Stetic.BinContainer.Attach(this);
            this.Name = "omvviewerlight.ChatLayout";
            // Container child omvviewerlight.ChatLayout.Gtk.Container+ContainerChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 500;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.chatconsole1 = new omvviewerlight.ChatConsole();
            this.chatconsole1.WidthRequest = 600;
            this.chatconsole1.Events = ((Gdk.EventMask)(256));
            this.chatconsole1.Name = "chatconsole1";
            this.hpaned1.Add(this.chatconsole1);
            Gtk.Paned.PanedChild w1 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.chatconsole1]));
            w1.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vpaned1 = new Gtk.VPaned();
            this.vpaned1.CanFocus = true;
            this.vpaned1.Name = "vpaned1";
            this.vpaned1.Position = 275;
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.friendslist1 = new omvviewerlight.FriendsList();
            this.friendslist1.Events = ((Gdk.EventMask)(256));
            this.friendslist1.Name = "friendslist1";
            this.vpaned1.Add(this.friendslist1);
            Gtk.Paned.PanedChild w2 = ((Gtk.Paned.PanedChild)(this.vpaned1[this.friendslist1]));
            w2.Resize = false;
            // Container child vpaned1.Gtk.Paned+PanedChild
            this.radar1 = new omvviewerlight.Radar();
            this.radar1.Events = ((Gdk.EventMask)(256));
            this.radar1.Name = "radar1";
            this.vpaned1.Add(this.radar1);
            this.hpaned1.Add(this.vpaned1);
            this.Add(this.hpaned1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
