// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class EventsSearch {
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label1;
        
        private Gtk.Entry entry1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label8;
        
        private Gtk.ComboBox combobox_category;
        
        private Gtk.HBox hbox4;
        
        private Gtk.CheckButton checkbutton_mature;
        
        private Gtk.Button button_search;
        
        private Gtk.Label label_info;
        
        private Gtk.HBox hbox5;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView treeview1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label6;
        
        private Gtk.Label label5;
        
        private Gtk.Label label7;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Entry entry_name;
        
        private Gtk.Entry entry_location;
        
        private Gtk.Entry entry_date;
        
        private Gtk.Entry entry_duration;
        
        private Gtk.Entry entry_organiser;
        
        private Gtk.Entry entry_cat;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TextView textview_eventinfo;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.EventsSearch
            Stetic.BinContainer.Attach(this);
            this.Name = "omvviewerlight.EventsSearch";
            // Container child omvviewerlight.EventsSearch.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Find");
            this.hbox3.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.entry1 = new Gtk.Entry();
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '●';
            this.hbox3.Add(this.entry1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.entry1]));
            w2.Position = 1;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Categories");
            this.hbox2.Add(this.label8);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.label8]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.combobox_category = Gtk.ComboBox.NewText();
            this.combobox_category.WidthRequest = 171;
            this.combobox_category.Name = "combobox_category";
            this.hbox2.Add(this.combobox_category);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.combobox_category]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.checkbutton_mature = new Gtk.CheckButton();
            this.checkbutton_mature.CanFocus = true;
            this.checkbutton_mature.Name = "checkbutton_mature";
            this.checkbutton_mature.Label = Mono.Unix.Catalog.GetString("Include Mature");
            this.checkbutton_mature.Active = true;
            this.checkbutton_mature.DrawIndicator = true;
            this.checkbutton_mature.UseUnderline = true;
            this.hbox4.Add(this.checkbutton_mature);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox4[this.checkbutton_mature]));
            w7.Position = 0;
            // Container child hbox4.Gtk.Box+BoxChild
            this.button_search = new Gtk.Button();
            this.button_search.CanFocus = true;
            this.button_search.Name = "button_search";
            this.button_search.UseUnderline = true;
            // Container child button_search.Gtk.Container+ContainerChild
            Gtk.Alignment w8 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w9 = new Gtk.HBox();
            w9.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w10 = new Gtk.Image();
            w10.Pixbuf = Gdk.Pixbuf.LoadFromResource("status_search_btn.png");
            w9.Add(w10);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w12 = new Gtk.Label();
            w12.LabelProp = Mono.Unix.Catalog.GetString("Search");
            w12.UseUnderline = true;
            w9.Add(w12);
            w8.Add(w9);
            this.button_search.Add(w8);
            this.hbox4.Add(this.button_search);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox4[this.button_search]));
            w16.Position = 2;
            w16.Expand = false;
            w16.Fill = false;
            this.vbox1.Add(this.hbox4);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
            w17.Position = 2;
            w17.Expand = false;
            w17.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label_info = new Gtk.Label();
            this.label_info.Name = "label_info";
            this.label_info.Xalign = 0.01F;
            this.label_info.LabelProp = Mono.Unix.Catalog.GetString("Type the name of events to search for and press the search button");
            this.vbox1.Add(this.label_info);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox1[this.label_info]));
            w18.Position = 3;
            w18.Expand = false;
            w18.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.treeview1 = new Gtk.TreeView();
            this.treeview1.WidthRequest = 350;
            this.treeview1.CanFocus = true;
            this.treeview1.Name = "treeview1";
            this.treeview1.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.treeview1);
            this.hbox5.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox5[this.GtkScrolledWindow]));
            w20.Position = 0;
            // Container child hbox5.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Homogeneous = true;
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Event Name");
            this.vbox3.Add(this.label2);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.vbox3[this.label2]));
            w21.Position = 0;
            w21.Expand = false;
            w21.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Location");
            this.vbox3.Add(this.label3);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox3[this.label3]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Date");
            this.vbox3.Add(this.label4);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox3[this.label4]));
            w23.Position = 2;
            w23.Expand = false;
            w23.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Duration");
            this.vbox3.Add(this.label6);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox3[this.label6]));
            w24.Position = 3;
            w24.Expand = false;
            w24.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Organiser");
            this.vbox3.Add(this.label5);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox3[this.label5]));
            w25.Position = 4;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Category");
            this.vbox3.Add(this.label7);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.vbox3[this.label7]));
            w26.Position = 5;
            w26.Expand = false;
            w26.Fill = false;
            this.hbox1.Add(this.vbox3);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
            w27.Position = 0;
            w27.Expand = false;
            w27.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.entry_name = new Gtk.Entry();
            this.entry_name.CanFocus = true;
            this.entry_name.Name = "entry_name";
            this.entry_name.IsEditable = false;
            this.entry_name.InvisibleChar = '●';
            this.vbox4.Add(this.entry_name);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox4[this.entry_name]));
            w28.Position = 0;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.entry_location = new Gtk.Entry();
            this.entry_location.CanFocus = true;
            this.entry_location.Name = "entry_location";
            this.entry_location.IsEditable = false;
            this.entry_location.InvisibleChar = '●';
            this.vbox4.Add(this.entry_location);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox4[this.entry_location]));
            w29.Position = 1;
            w29.Expand = false;
            w29.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.entry_date = new Gtk.Entry();
            this.entry_date.CanFocus = true;
            this.entry_date.Name = "entry_date";
            this.entry_date.IsEditable = false;
            this.entry_date.InvisibleChar = '●';
            this.vbox4.Add(this.entry_date);
            Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.vbox4[this.entry_date]));
            w30.Position = 2;
            w30.Expand = false;
            w30.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.entry_duration = new Gtk.Entry();
            this.entry_duration.CanFocus = true;
            this.entry_duration.Name = "entry_duration";
            this.entry_duration.IsEditable = false;
            this.entry_duration.InvisibleChar = '●';
            this.vbox4.Add(this.entry_duration);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox4[this.entry_duration]));
            w31.Position = 3;
            w31.Expand = false;
            w31.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.entry_organiser = new Gtk.Entry();
            this.entry_organiser.CanFocus = true;
            this.entry_organiser.Name = "entry_organiser";
            this.entry_organiser.IsEditable = false;
            this.entry_organiser.InvisibleChar = '●';
            this.vbox4.Add(this.entry_organiser);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.vbox4[this.entry_organiser]));
            w32.Position = 4;
            w32.Expand = false;
            w32.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.entry_cat = new Gtk.Entry();
            this.entry_cat.CanFocus = true;
            this.entry_cat.Name = "entry_cat";
            this.entry_cat.IsEditable = false;
            this.entry_cat.InvisibleChar = '●';
            this.vbox4.Add(this.entry_cat);
            Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.vbox4[this.entry_cat]));
            w33.Position = 5;
            w33.Expand = false;
            w33.Fill = false;
            this.hbox1.Add(this.vbox4);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
            w34.Position = 1;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w35.Position = 0;
            w35.Expand = false;
            w35.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.textview_eventinfo = new Gtk.TextView();
            this.textview_eventinfo.CanFocus = true;
            this.textview_eventinfo.Name = "textview_eventinfo";
            this.textview_eventinfo.Editable = false;
            this.textview_eventinfo.CursorVisible = false;
            this.textview_eventinfo.WrapMode = ((Gtk.WrapMode)(2));
            this.GtkScrolledWindow1.Add(this.textview_eventinfo);
            this.vbox2.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
            w37.Position = 1;
            this.hbox5.Add(this.vbox2);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox5[this.vbox2]));
            w38.Position = 1;
            this.vbox1.Add(this.hbox5);
            Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
            w39.Position = 4;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.button_search.Clicked += new System.EventHandler(this.OnButtonSearchClicked);
            this.treeview1.CursorChanged += new System.EventHandler(this.OnTreeview1CursorChanged);
        }
    }
}
