// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class ScriptDialogue {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Label label1;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Button button15;
        
        private Gtk.Button button16;
        
        private Gtk.Button button17;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Button button12;
        
        private Gtk.Button button13;
        
        private Gtk.Button button14;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button button9;
        
        private Gtk.Button button10;
        
        private Gtk.Button button11;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Button button6;
        
        private Gtk.Button button7;
        
        private Gtk.Button button8;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.ScriptDialogue
            this.Name = "omvviewerlight.ScriptDialogue";
            this.Title = Mono.Unix.Catalog.GetString("ScriptDialogue");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child omvviewerlight.ScriptDialogue.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.WidthRequest = 398;
            this.label1.HeightRequest = 105;
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("label1");
            this.label1.Wrap = true;
            this.label1.Justify = ((Gtk.Justification)(2));
            this.vbox1.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Homogeneous = true;
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button15 = new Gtk.Button();
            this.button15.CanFocus = true;
            this.button15.Name = "button15";
            this.button15.UseUnderline = true;
            this.button15.Label = Mono.Unix.Catalog.GetString("button15");
            this.hbox3.Add(this.button15);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.button15]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button16 = new Gtk.Button();
            this.button16.CanFocus = true;
            this.button16.Name = "button16";
            this.button16.UseUnderline = true;
            this.button16.Label = Mono.Unix.Catalog.GetString("button16");
            this.hbox3.Add(this.button16);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox3[this.button16]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.button17 = new Gtk.Button();
            this.button17.CanFocus = true;
            this.button17.Name = "button17";
            this.button17.UseUnderline = true;
            this.button17.Label = Mono.Unix.Catalog.GetString("button17");
            this.hbox3.Add(this.button17);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox3[this.button17]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Homogeneous = true;
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.button12 = new Gtk.Button();
            this.button12.CanFocus = true;
            this.button12.Name = "button12";
            this.button12.UseUnderline = true;
            this.button12.Label = Mono.Unix.Catalog.GetString("button12");
            this.hbox2.Add(this.button12);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.button12]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.button13 = new Gtk.Button();
            this.button13.CanFocus = true;
            this.button13.Name = "button13";
            this.button13.UseUnderline = true;
            this.button13.Label = Mono.Unix.Catalog.GetString("button13");
            this.hbox2.Add(this.button13);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.button13]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.button14 = new Gtk.Button();
            this.button14.CanFocus = true;
            this.button14.Name = "button14";
            this.button14.UseUnderline = true;
            this.button14.Label = Mono.Unix.Catalog.GetString("button14");
            this.hbox2.Add(this.button14);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox2[this.button14]));
            w8.Position = 2;
            w8.Expand = false;
            w8.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Homogeneous = true;
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button9 = new Gtk.Button();
            this.button9.CanFocus = true;
            this.button9.Name = "button9";
            this.button9.UseUnderline = true;
            this.button9.Label = Mono.Unix.Catalog.GetString("button9");
            this.hbox1.Add(this.button9);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox1[this.button9]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button10 = new Gtk.Button();
            this.button10.CanFocus = true;
            this.button10.Name = "button10";
            this.button10.UseUnderline = true;
            this.button10.Label = Mono.Unix.Catalog.GetString("button10");
            this.hbox1.Add(this.button10);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.button10]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.button11 = new Gtk.Button();
            this.button11.CanFocus = true;
            this.button11.Name = "button11";
            this.button11.UseUnderline = true;
            this.button11.Label = Mono.Unix.Catalog.GetString("button11");
            this.hbox1.Add(this.button11);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.button11]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w13.Position = 3;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Homogeneous = true;
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.button6 = new Gtk.Button();
            this.button6.CanFocus = true;
            this.button6.Name = "button6";
            this.button6.UseUnderline = true;
            this.button6.Label = Mono.Unix.Catalog.GetString("button6");
            this.hbox4.Add(this.button6);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox4[this.button6]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.button7 = new Gtk.Button();
            this.button7.CanFocus = true;
            this.button7.Name = "button7";
            this.button7.UseUnderline = true;
            this.button7.Label = Mono.Unix.Catalog.GetString("button7");
            this.hbox4.Add(this.button7);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox4[this.button7]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.button8 = new Gtk.Button();
            this.button8.CanFocus = true;
            this.button8.Name = "button8";
            this.button8.UseUnderline = true;
            this.button8.Label = Mono.Unix.Catalog.GetString("button8");
            this.hbox4.Add(this.button8);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox4[this.button8]));
            w16.Position = 2;
            w16.Expand = false;
            w16.Fill = false;
            this.vbox1.Add(this.hbox4);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
            w17.Position = 4;
            w17.Expand = false;
            w17.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 431;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
