// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class Inventory {
        
        private Gtk.HBox hbox1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView treeview_inv;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox5;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox6;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Label label11;
        
        private Gtk.Label label2;
        
        private Gtk.Label label4;
        
        private Gtk.VBox vbox5;
        
        private Gtk.Label label_name;
        
        private Gtk.Label label_createdby;
        
        private Gtk.Label label_aquired;
        
        private Gtk.Label label_group;
        
        private Gtk.Label label_saleprice;
        
        private Gtk.HBox hbox4;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label14;
        
        private Gtk.VBox vbox7;
        
        private Gtk.CheckButton checkbutton_copynext;
        
        private Gtk.CheckButton checkbutton_modnext;
        
        private Gtk.CheckButton checkbutton_transnext;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label13;
        
        private Gtk.VBox vbox6;
        
        private Gtk.CheckButton checkbutton_copy;
        
        private Gtk.CheckButton checkbutton_mod;
        
        private Gtk.CheckButton checkbutton_trans;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.Inventory
            Stetic.BinContainer.Attach(this);
            this.Name = "omvviewerlight.Inventory";
            // Container child omvviewerlight.Inventory.Gtk.Container+ContainerChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.treeview_inv = new Gtk.TreeView();
            this.treeview_inv.WidthRequest = 450;
            this.treeview_inv.CanFocus = true;
            this.treeview_inv.Name = "treeview_inv";
            this.treeview_inv.HeadersClickable = true;
            this.GtkScrolledWindow.Add(this.treeview_inv);
            this.vbox2.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
            w2.Position = 0;
            this.hbox1.Add(this.vbox2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
            w3.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.WidthRequest = 81;
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Name");
            this.vbox3.Add(this.label7);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.label7]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 0F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Created By");
            this.vbox3.Add(this.label8);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.label8]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.Xalign = 0F;
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Aquired");
            this.vbox3.Add(this.label11);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.label11]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Group");
            this.vbox3.Add(this.label2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox3[this.label2]));
            w7.Position = 3;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Sale price");
            this.vbox3.Add(this.label4);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox3[this.label4]));
            w8.Position = 4;
            w8.Expand = false;
            w8.Fill = false;
            this.hbox6.Add(this.vbox3);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox6[this.vbox3]));
            w9.Position = 0;
            w9.Expand = false;
            w9.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.WidthRequest = 175;
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.label_name = new Gtk.Label();
            this.label_name.Name = "label_name";
            this.label_name.Xalign = 0F;
            this.label_name.LabelProp = Mono.Unix.Catalog.GetString("label9");
            this.vbox5.Add(this.label_name);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox5[this.label_name]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.label_createdby = new Gtk.Label();
            this.label_createdby.Name = "label_createdby";
            this.label_createdby.Xalign = 0F;
            this.label_createdby.LabelProp = Mono.Unix.Catalog.GetString("label10");
            this.vbox5.Add(this.label_createdby);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox5[this.label_createdby]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.label_aquired = new Gtk.Label();
            this.label_aquired.Name = "label_aquired";
            this.label_aquired.Xalign = 0F;
            this.label_aquired.LabelProp = Mono.Unix.Catalog.GetString("label12");
            this.vbox5.Add(this.label_aquired);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox5[this.label_aquired]));
            w12.Position = 2;
            w12.Expand = false;
            w12.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.label_group = new Gtk.Label();
            this.label_group.Name = "label_group";
            this.label_group.Xalign = 0F;
            this.label_group.LabelProp = Mono.Unix.Catalog.GetString("label3");
            this.vbox5.Add(this.label_group);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox5[this.label_group]));
            w13.Position = 3;
            w13.Expand = false;
            w13.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.label_saleprice = new Gtk.Label();
            this.label_saleprice.Name = "label_saleprice";
            this.label_saleprice.Xalign = 0F;
            this.label_saleprice.Yalign = 0F;
            this.label_saleprice.LabelProp = Mono.Unix.Catalog.GetString("label5");
            this.vbox5.Add(this.label_saleprice);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox5[this.label_saleprice]));
            w14.Position = 4;
            w14.Expand = false;
            w14.Fill = false;
            this.hbox6.Add(this.vbox5);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox6[this.vbox5]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            this.vbox4.Add(this.hbox6);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            this.hbox5.Add(this.vbox4);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox5[this.vbox4]));
            w17.Position = 0;
            w17.Expand = false;
            w17.Fill = false;
            this.vbox1.Add(this.hbox5);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
            w18.Position = 0;
            w18.Expand = false;
            w18.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            this.vbox1.Add(this.hbox4);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
            w19.PackType = ((Gtk.PackType)(1));
            w19.Position = 1;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label14 = new Gtk.Label();
            this.label14.WidthRequest = 78;
            this.label14.Name = "label14";
            this.label14.Xalign = 0F;
            this.label14.LabelProp = Mono.Unix.Catalog.GetString("Next owner\npermissions");
            this.hbox3.Add(this.label14);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox3[this.label14]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.vbox7 = new Gtk.VBox();
            this.vbox7.Name = "vbox7";
            this.vbox7.Spacing = -7;
            // Container child vbox7.Gtk.Box+BoxChild
            this.checkbutton_copynext = new Gtk.CheckButton();
            this.checkbutton_copynext.Name = "checkbutton_copynext";
            this.checkbutton_copynext.Label = Mono.Unix.Catalog.GetString("Copy");
            this.checkbutton_copynext.DrawIndicator = true;
            this.checkbutton_copynext.UseUnderline = true;
            this.vbox7.Add(this.checkbutton_copynext);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.vbox7[this.checkbutton_copynext]));
            w21.Position = 0;
            w21.Expand = false;
            w21.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.checkbutton_modnext = new Gtk.CheckButton();
            this.checkbutton_modnext.Name = "checkbutton_modnext";
            this.checkbutton_modnext.Label = Mono.Unix.Catalog.GetString("Modify");
            this.checkbutton_modnext.DrawIndicator = true;
            this.checkbutton_modnext.UseUnderline = true;
            this.vbox7.Add(this.checkbutton_modnext);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox7[this.checkbutton_modnext]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.checkbutton_transnext = new Gtk.CheckButton();
            this.checkbutton_transnext.Name = "checkbutton_transnext";
            this.checkbutton_transnext.Label = Mono.Unix.Catalog.GetString("Transfer");
            this.checkbutton_transnext.DrawIndicator = true;
            this.checkbutton_transnext.UseUnderline = true;
            this.vbox7.Add(this.checkbutton_transnext);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox7[this.checkbutton_transnext]));
            w23.Position = 2;
            w23.Expand = false;
            w23.Fill = false;
            this.hbox3.Add(this.vbox7);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox3[this.vbox7]));
            w24.Position = 1;
            this.vbox1.Add(this.hbox3);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
            w25.PackType = ((Gtk.PackType)(1));
            w25.Position = 2;
            w25.Expand = false;
            w25.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label13 = new Gtk.Label();
            this.label13.WidthRequest = 78;
            this.label13.Name = "label13";
            this.label13.Xalign = 0F;
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("My\npermissions");
            this.hbox2.Add(this.label13);
            Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox2[this.label13]));
            w26.Position = 0;
            w26.Expand = false;
            w26.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = -7;
            // Container child vbox6.Gtk.Box+BoxChild
            this.checkbutton_copy = new Gtk.CheckButton();
            this.checkbutton_copy.Sensitive = false;
            this.checkbutton_copy.Name = "checkbutton_copy";
            this.checkbutton_copy.Label = Mono.Unix.Catalog.GetString("Copy");
            this.checkbutton_copy.DrawIndicator = true;
            this.checkbutton_copy.UseUnderline = true;
            this.vbox6.Add(this.checkbutton_copy);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox6[this.checkbutton_copy]));
            w27.Position = 0;
            w27.Expand = false;
            w27.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.checkbutton_mod = new Gtk.CheckButton();
            this.checkbutton_mod.Sensitive = false;
            this.checkbutton_mod.Name = "checkbutton_mod";
            this.checkbutton_mod.Label = Mono.Unix.Catalog.GetString("Modify");
            this.checkbutton_mod.DrawIndicator = true;
            this.checkbutton_mod.UseUnderline = true;
            this.vbox6.Add(this.checkbutton_mod);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox6[this.checkbutton_mod]));
            w28.Position = 1;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vbox6.Gtk.Box+BoxChild
            this.checkbutton_trans = new Gtk.CheckButton();
            this.checkbutton_trans.Sensitive = false;
            this.checkbutton_trans.Name = "checkbutton_trans";
            this.checkbutton_trans.Label = Mono.Unix.Catalog.GetString("Transfer");
            this.checkbutton_trans.DrawIndicator = true;
            this.checkbutton_trans.UseUnderline = true;
            this.vbox6.Add(this.checkbutton_trans);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox6[this.checkbutton_trans]));
            w29.Position = 2;
            w29.Expand = false;
            w29.Fill = false;
            this.hbox2.Add(this.vbox6);
            Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox6]));
            w30.Position = 1;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w31.PackType = ((Gtk.PackType)(1));
            w31.Position = 3;
            w31.Expand = false;
            w31.Fill = false;
            this.hbox1.Add(this.vbox1);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
            w32.Position = 1;
            w32.Expand = false;
            w32.Fill = false;
            this.Add(this.hbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.treeview_inv.CursorChanged += new System.EventHandler(this.OnTreeviewInvCursorChanged);
        }
    }
}
