// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class ScaleImage {
        
        private Gtk.EventBox eventbox2;
        
        private Gtk.Image dispimage;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.ScaleImage
            Stetic.BinContainer.Attach(this);
            this.Name = "omvviewerlight.ScaleImage";
            // Container child omvviewerlight.ScaleImage.Gtk.Container+ContainerChild
            this.eventbox2 = new Gtk.EventBox();
            this.eventbox2.Name = "eventbox2";
            // Container child eventbox2.Gtk.Container+ContainerChild
            this.dispimage = new Gtk.Image();
            this.dispimage.Name = "dispimage";
            this.eventbox2.Add(this.dispimage);
            this.Add(this.eventbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
