// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace omvviewerlight {
    
    
    public partial class Preferences {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.VBox vbox3;
        
        private Gtk.CheckButton checkbutton_showtimestamps;
        
        private Gtk.Label GtkLabel1;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.VBox vbox4;
        
        private Gtk.CheckButton checkbutton_hideminimise;
        
        private Gtk.RadioButton radiobutton1;
        
        private Gtk.RadioButton radiobutton2;
        
        private Gtk.Label GtkLabel2;
        
        private Gtk.Label label2;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget omvviewerlight.Preferences
            this.Name = "omvviewerlight.Preferences";
            this.Title = Mono.Unix.Catalog.GetString("Preferences");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child omvviewerlight.Preferences.Gtk.Container+ContainerChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.checkbutton_showtimestamps = new Gtk.CheckButton();
            this.checkbutton_showtimestamps.CanFocus = true;
            this.checkbutton_showtimestamps.Name = "checkbutton_showtimestamps";
            this.checkbutton_showtimestamps.Label = Mono.Unix.Catalog.GetString("Show time stamps in chat and IMs");
            this.checkbutton_showtimestamps.DrawIndicator = true;
            this.checkbutton_showtimestamps.UseUnderline = true;
            this.vbox3.Add(this.checkbutton_showtimestamps);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox3[this.checkbutton_showtimestamps]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.GtkAlignment.Add(this.vbox3);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>Chat and IMs</b>");
            this.GtkLabel1.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel1;
            this.vbox2.Add(this.frame1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.checkbutton_hideminimise = new Gtk.CheckButton();
            this.checkbutton_hideminimise.CanFocus = true;
            this.checkbutton_hideminimise.Name = "checkbutton_hideminimise";
            this.checkbutton_hideminimise.Label = Mono.Unix.Catalog.GetString("Hide minimise confirm");
            this.checkbutton_hideminimise.DrawIndicator = true;
            this.checkbutton_hideminimise.UseUnderline = true;
            this.vbox4.Add(this.checkbutton_hideminimise);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox4[this.checkbutton_hideminimise]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.radiobutton1 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Default is to minimise"));
            this.radiobutton1.CanFocus = true;
            this.radiobutton1.Name = "radiobutton1";
            this.radiobutton1.DrawIndicator = true;
            this.radiobutton1.UseUnderline = true;
            this.radiobutton1.Group = new GLib.SList(System.IntPtr.Zero);
            this.vbox4.Add(this.radiobutton1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox4[this.radiobutton1]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.radiobutton2 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("Default is to close"));
            this.radiobutton2.CanFocus = true;
            this.radiobutton2.Name = "radiobutton2";
            this.radiobutton2.DrawIndicator = true;
            this.radiobutton2.UseUnderline = true;
            this.radiobutton2.Group = this.radiobutton1.Group;
            this.vbox4.Add(this.radiobutton2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox4[this.radiobutton2]));
            w7.Position = 2;
            w7.Expand = false;
            w7.Fill = false;
            this.GtkAlignment1.Add(this.vbox4);
            this.frame2.Add(this.GtkAlignment1);
            this.GtkLabel2 = new Gtk.Label();
            this.GtkLabel2.Name = "GtkLabel2";
            this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>Minimise</b>");
            this.GtkLabel2.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel2;
            this.vbox2.Add(this.frame2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.notebook1.Add(this.vbox2);
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("page1");
            this.notebook1.SetTabLabel(this.vbox2, this.label2);
            this.label2.ShowAll();
            this.Add(this.notebook1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.checkbutton_showtimestamps.Clicked += new System.EventHandler(this.OnCheckbuttonShowtimestampsClicked);
            this.checkbutton_hideminimise.Clicked += new System.EventHandler(this.OnCheckbuttonHideminimiseClicked);
            this.radiobutton1.Activated += new System.EventHandler(this.OnRadiobutton1Activated);
            this.radiobutton2.Activated += new System.EventHandler(this.OnRadiobutton2Activated);
        }
    }
}
